package hackathon

import (
	"fmt"
	"strings"
	"testing"
)

func boolPtr(b bool) *bool { return &b }

func addedPatch(lines ...string) string {
	var b strings.Builder
	b.WriteString("--- a/f\n+++ b/f\n")
	for _, l := range lines {
		b.WriteString("+" + l + "\n")
	}
	return b.String()
}

// --- §5.3 diff_stats: computed in code, never estimated by the model ---

func TestComputeDiffStats_ExcludesLockfileGeneratedAndWhitespace(t *testing.T) {
	files := []FileChange{
		{Filename: "src/auth/login.go", Patch: addedPatch("func Login() {", "  return nil", "}")},
		{Filename: "package-lock.json", Patch: addedPatch(strings.Repeat("dep", 1), "more", "lines")},
		{Filename: "api/gen.pb.go", Patch: "--- a/f\n+++ b/f\n+// Code generated by protoc. DO NOT EDIT.\n+type X struct{}\n"},
		{Filename: "src/style.css", Patch: addedPatch("", "   ", "")},
	}
	s := ComputeDiffStats(files)

	if s.FilesChanged != 4 {
		t.Errorf("FilesChanged = %d, want 4", s.FilesChanged)
	}
	if s.LockfileLines != 3 {
		t.Errorf("LockfileLines = %d, want 3", s.LockfileLines)
	}
	if s.GeneratedLines != 2 {
		t.Errorf("GeneratedLines = %d, want 2 (the generated banner counts the whole file)", s.GeneratedLines)
	}
	// Only the 3 real Go lines count: lockfile, generated and whitespace-only
	// additions are all excluded. This is the number that stops a PR
	// misrepresenting its own size.
	if s.MeaningfulLines != 3 {
		t.Errorf("MeaningfulLines = %d, want 3", s.MeaningfulLines)
	}
	if !s.TouchesCorePath {
		t.Error("TouchesCorePath = false despite a change under src/")
	}
}

func TestComputeDiffStats_DetectsTestsAndDocsOnly(t *testing.T) {
	withTests := ComputeDiffStats([]FileChange{
		{Filename: "internal/api/handler.go", Patch: addedPatch("x := 1")},
		{Filename: "internal/api/handler_test.go", Patch: addedPatch("func TestX(t *testing.T) {}")},
	})
	if !withTests.TestsAdded || withTests.TestLines == 0 {
		t.Errorf("TestsAdded=%v TestLines=%d, want tests detected", withTests.TestsAdded, withTests.TestLines)
	}
	if withTests.DocsOnly {
		t.Error("DocsOnly = true for a change that includes code")
	}

	docsOnly := ComputeDiffStats([]FileChange{
		{Filename: "README.md", Patch: addedPatch("Some prose.")},
		{Filename: "docs/guide.md", Patch: addedPatch("More prose.")},
	})
	if !docsOnly.DocsOnly {
		t.Error("DocsOnly = false for a docs-only change")
	}
}

func TestComputeDiffStats_FallsBackToGitHubCountsWithoutAPatch(t *testing.T) {
	// GitHub omits the patch for binary files and very large diffs; the
	// change is still real and must not read as zero.
	s := ComputeDiffStats([]FileChange{{Filename: "src/img.png", Additions: 40, Deletions: 5}})
	if s.LinesAdded != 40 || s.LinesRemoved != 5 {
		t.Errorf("got +%d/-%d, want +40/-5", s.LinesAdded, s.LinesRemoved)
	}
}

// --- §5.1 pre-filter ---

func TestPrefilter_Section51(t *testing.T) {
	good := PrefilterInput{
		Stats:                       DiffStats{MeaningfulLines: 30},
		CIPassed:                    boolPtr(true),
		LinkedToGrainHackIssue:      true,
		AuthorIsAssignedContributor: true,
	}

	if res := Prefilter(good); res.Rejected {
		t.Fatalf("a clean PR was rejected: %s", res.Reason)
	}

	tests := []struct {
		name   string
		mutate func(*PrefilterInput)
		want   string
	}{
		{"unassigned author", func(in *PrefilterInput) { in.AuthorIsAssignedContributor = false }, "not the contributor assigned"},
		{"no linked issue", func(in *PrefilterInput) { in.LinkedToGrainHackIssue = false }, "not linked to a GrainHack issue"},
		{"issue author", func(in *PrefilterInput) { in.AuthorIsIssueAuthor = true }, "opened the issue"},
		{"repo admin", func(in *PrefilterInput) { in.AuthorIsRepoAdmin = true }, "admin of the repository"},
		{"failing CI", func(in *PrefilterInput) { in.CIPassed = boolPtr(false) }, "CI was failing"},
		{"docs only", func(in *PrefilterInput) { in.Stats.DocsOnly = true }, "documentation only"},
		{"no meaningful lines", func(in *PrefilterInput) { in.Stats.MeaningfulLines = 0 }, "no meaningful code changes"},
		{"below the minimum size", func(in *PrefilterInput) {
			in.Stats.MeaningfulLines = 3
			in.MinMeaningfulLines = 10
		}, "below this event's minimum"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			in := good
			tc.mutate(&in)
			res := Prefilter(in)
			if !res.Rejected {
				t.Fatalf("expected rejection")
			}
			if !strings.Contains(res.Reason, tc.want) {
				t.Errorf("reason = %q, want it to mention %q", res.Reason, tc.want)
			}
		})
	}
}

// Unknown CI is not failing CI. Rejecting on it would punish every repo
// without CI configured.
func TestPrefilter_UnknownCIIsNotAFailure(t *testing.T) {
	in := PrefilterInput{
		Stats:                       DiffStats{MeaningfulLines: 30},
		CIPassed:                    nil,
		LinkedToGrainHackIssue:      true,
		AuthorIsAssignedContributor: true,
	}
	if res := Prefilter(in); res.Rejected {
		t.Errorf("unknown CI state rejected the PR: %s", res.Reason)
	}
}

// §5.1's own parenthetical: docs-only is fine when the issue was a docs issue.
func TestPrefilter_DocsOnlyAllowedForADocsIssue(t *testing.T) {
	in := PrefilterInput{
		Stats:                       DiffStats{MeaningfulLines: 12, DocsOnly: true},
		CIPassed:                    boolPtr(true),
		LinkedToGrainHackIssue:      true,
		AuthorIsAssignedContributor: true,
		IssueWasDocsIssue:           true,
	}
	if res := Prefilter(in); res.Rejected {
		t.Errorf("docs PR for a docs issue rejected: %s", res.Reason)
	}
}

// --- §5.2 duplicate detection ---

func TestFindDuplicates_FlagsNearIdenticalAcrossAccounts(t *testing.T) {
	body := addedPatch(
		"func retryWithBackoff(ctx context.Context, attempts int) error {",
		"  for i := 0; i < attempts; i++ {",
		"    if err := do(ctx); err == nil { return nil }",
		"    time.Sleep(backoff(i))",
		"  }",
		"  return ErrExhausted",
		"}",
	)
	// Same code, different indentation and a renamed variable - the shape a
	// copied submission actually takes.
	copied := strings.ReplaceAll(strings.ReplaceAll(body, "  ", " "), "attempts", "tries")
	unrelated := addedPatch("const Theme = 'dark'", "export default Theme")

	pairs := FindDuplicates([]DuplicateCandidate{
		{VerdictID: "v1", Login: "alice", Diff: body},
		{VerdictID: "v2", Login: "bob", Diff: copied},
		{VerdictID: "v3", Login: "carol", Diff: unrelated},
	}, 0.5, nil)

	if len(pairs) != 1 {
		t.Fatalf("got %d flagged pairs, want 1: %+v", len(pairs), pairs)
	}
	if pairs[0].EarlierVerdictID != "v1" || pairs[0].LaterVerdictID != "v2" {
		t.Errorf("flagged %s/%s, want v1/v2 with the later one flagged", pairs[0].EarlierVerdictID, pairs[0].LaterVerdictID)
	}
	if pairs[0].SameAuthor {
		t.Error("SameAuthor = true for two different accounts - cross-account duplication is the farming case")
	}
}

func TestFindDuplicates_LeavesUnrelatedWorkAlone(t *testing.T) {
	pairs := FindDuplicates([]DuplicateCandidate{
		{VerdictID: "v1", Login: "alice", Diff: addedPatch("func Alpha() int { return 1 }")},
		{VerdictID: "v2", Login: "bob", Diff: addedPatch("class Beta extends Gamma {}")},
	}, 0.92, nil)
	if len(pairs) != 0 {
		t.Errorf("flagged unrelated work: %+v", pairs)
	}
}

func TestFindDuplicates_MarksSameAuthorPairsDistinctly(t *testing.T) {
	d := addedPatch("func Same() {}", "// identical body", "var x = 1")
	pairs := FindDuplicates([]DuplicateCandidate{
		{VerdictID: "v1", Login: "alice", Diff: d},
		{VerdictID: "v2", Login: "Alice", Diff: d},
	}, 0.5, nil)
	if len(pairs) != 1 {
		t.Fatalf("got %d pairs, want 1", len(pairs))
	}
	// One person splitting work across PRs is a different problem from a
	// farm, and a reviewer has to be able to tell them apart.
	if !pairs[0].SameAuthor {
		t.Error("SameAuthor = false for the same login in different case")
	}
}

func TestLexicalSimilarity_IdenticalAndDisjoint(t *testing.T) {
	d := addedPatch("alpha beta gamma delta epsilon zeta", "eta theta iota kappa")
	if got := LexicalSimilarity(d, d); got != 1 {
		t.Errorf("identical diffs scored %v, want 1", got)
	}
	if got := LexicalSimilarity(d, addedPatch("completely different words here entirely", "nothing shared at all")); got != 0 {
		t.Errorf("disjoint diffs scored %v, want 0", got)
	}
	if got := LexicalSimilarity("", d); got != 0 {
		t.Errorf("empty diff scored %v, want 0", got)
	}
}

// --- §5.8 payout ---

func specPayoutConfig() map[string]string {
	return map[string]string{
		"units_rejected": "0", "units_accepted": "1", "units_substantial": "3", "units_exceptional": "5",
		"payout_floor": "50", "payout_floor_strategy": "fund_highest_buckets_first",
	}
}

// TestComputePayout_SpecWorkedExample reproduces §5.8's own table exactly:
// 40 accepted, 12 substantial, 3 exceptional, $10,000 pool -> 91 units,
// unit value $109.89, so accepted $110 / substantial $330 / exceptional $549.
func TestComputePayout_SpecWorkedExample(t *testing.T) {
	var prs []JudgedPR
	add := func(n int, bucket string) {
		for i := 0; i < n; i++ {
			prs = append(prs, JudgedPR{VerdictID: fmt.Sprintf("%s-%d", bucket, i), Login: fmt.Sprintf("u%s%d", bucket[:1], i), Bucket: bucket})
		}
	}
	add(40, "accepted")
	add(12, "substantial")
	add(3, "exceptional")

	plan, err := ComputePayout(prs, 10000, specPayoutConfig())
	if err != nil {
		t.Fatalf("ComputePayout: %v", err)
	}
	if plan.TotalUnits != 91 {
		t.Errorf("TotalUnits = %d, want 91", plan.TotalUnits)
	}
	if got := round2(plan.UnitValue); got != 109.89 {
		t.Errorf("UnitValue = %v, want 109.89", got)
	}
	if plan.FloorApplied {
		t.Error("floor applied when the unit value was comfortably above it")
	}

	amounts := map[string]float64{}
	for _, e := range plan.Entries {
		amounts[e.Bucket] = e.Amount
		if !e.Funded {
			t.Errorf("%s entry unfunded with an adequate pool", e.Bucket)
		}
	}
	// The spec's rounded figures.
	if amounts["accepted"] != 109.89 || amounts["substantial"] != 329.67 || amounts["exceptional"] != 549.45 {
		t.Errorf("per-bucket amounts = %+v, want ~110/330/549", amounts)
	}
}

func TestComputePayout_RejectedTakeNoShare(t *testing.T) {
	plan, err := ComputePayout([]JudgedPR{
		{VerdictID: "a", Login: "alice", Bucket: "accepted"},
		{VerdictID: "r", Login: "mallory", Bucket: "rejected"},
	}, 100, specPayoutConfig())
	if err != nil {
		t.Fatalf("ComputePayout: %v", err)
	}
	if plan.TotalUnits != 1 {
		t.Errorf("TotalUnits = %d, want 1 - a rejected PR contributes no units", plan.TotalUnits)
	}
	for _, e := range plan.Entries {
		if e.Bucket == "rejected" && (e.Amount != 0 || e.Funded) {
			t.Errorf("rejected entry was paid %v (funded=%v)", e.Amount, e.Funded)
		}
	}
}

// The floor is the part that generates bad press if it's wrong: nobody
// should be silently paid a token amount for real work.
func TestComputePayout_FloorFundsHighestBucketsFirst(t *testing.T) {
	var prs []JudgedPR
	prs = append(prs, JudgedPR{VerdictID: "e1", Login: "exceptional-one", Bucket: "exceptional"})
	prs = append(prs, JudgedPR{VerdictID: "s1", Login: "substantial-one", Bucket: "substantial"})
	for i := 0; i < 20; i++ {
		prs = append(prs, JudgedPR{VerdictID: fmt.Sprintf("a%d", i), Login: fmt.Sprintf("accepted-%02d", i), Bucket: "accepted"})
	}

	// 5 + 3 + 20 = 28 units. A $500 pool gives $17.86/unit, well under the
	// $50 floor, so the floor strategy has to kick in.
	plan, err := ComputePayout(prs, 500, specPayoutConfig())
	if err != nil {
		t.Fatalf("ComputePayout: %v", err)
	}
	if !plan.FloorApplied {
		t.Fatal("floor not applied despite a unit value below it")
	}
	if plan.UnitValue != 50 {
		t.Errorf("UnitValue = %v, want the floor of 50", plan.UnitValue)
	}

	byID := map[string]PayoutEntry{}
	total := 0.0
	for _, e := range plan.Entries {
		byID[e.VerdictID] = e
		total += e.Amount
	}
	// Highest buckets first: exceptional (5 x 50 = 250) and substantial
	// (3 x 50 = 150) are funded before any accepted entry.
	if !byID["e1"].Funded || byID["e1"].Amount != 250 {
		t.Errorf("exceptional entry = %+v, want funded at 250", byID["e1"])
	}
	if !byID["s1"].Funded || byID["s1"].Amount != 150 {
		t.Errorf("substantial entry = %+v, want funded at 150", byID["s1"])
	}
	// 500 - 250 - 150 = 100 left, so exactly 2 accepted entries at 50.
	funded := 0
	for _, e := range plan.Entries {
		if e.Bucket == "accepted" && e.Funded {
			funded++
			if e.Amount != 50 {
				t.Errorf("accepted entry paid %v, want the floor of 50", e.Amount)
			}
		}
	}
	if funded != 2 {
		t.Errorf("funded accepted entries = %d, want 2", funded)
	}
	if plan.UnfundedCount != 18 {
		t.Errorf("UnfundedCount = %d, want 18", plan.UnfundedCount)
	}
	if total > 500.0001 {
		t.Errorf("paid out %v, which exceeds the %v pool", total, 500.0)
	}
	if plan.Note == "" {
		t.Error("no note explaining why the floor was applied - this is the rule that has to be explainable")
	}
}

func TestComputePayout_NoQualifyingSubmissions(t *testing.T) {
	plan, err := ComputePayout([]JudgedPR{{VerdictID: "r", Login: "x", Bucket: "rejected"}}, 1000, specPayoutConfig())
	if err != nil {
		t.Fatalf("ComputePayout: %v", err)
	}
	if plan.TotalUnits != 0 || plan.UnitValue != 0 {
		t.Errorf("plan = %+v, want zero units and no division", plan)
	}
	if plan.Note == "" {
		t.Error("expected a note explaining that nothing was divided")
	}
}

func TestComputePayout_ZeroPoolPaysNothingButStillRanks(t *testing.T) {
	plan, err := ComputePayout([]JudgedPR{
		{VerdictID: "a", Login: "alice", Bucket: "substantial"},
	}, 0, specPayoutConfig())
	if err != nil {
		t.Fatalf("ComputePayout: %v", err)
	}
	// A $0 test event still produces a full plan; it just pays nothing.
	if plan.TotalUnits != 3 {
		t.Errorf("TotalUnits = %d, want 3", plan.TotalUnits)
	}
	for _, e := range plan.Entries {
		if e.Amount != 0 {
			t.Errorf("paid %v from a zero pool", e.Amount)
		}
	}
}

// A zero-value PrefilterInput must enforce every §2.4 gate.
//
// Regression test for a design error caught by the existing suite: the
// toggles were first written as positives (RequireCIPass), so any caller that
// omitted them disabled every qualification gate. On the path that decides
// who gets paid, a forgotten field must fail toward rejecting, never toward
// paying.
func TestPrefilter_ZeroValueEnforcesEveryGate(t *testing.T) {
	failing := false

	// Unlinked PR, zero-value toggles.
	if res := Prefilter(PrefilterInput{
		AuthorIsAssignedContributor: true,
		Stats:                       DiffStats{MeaningfulLines: 50},
	}); !res.Rejected {
		t.Error("an unlinked PR passed with zero-value toggles; the gate defaulted to off")
	}

	// Failing CI, zero-value toggles.
	if res := Prefilter(PrefilterInput{
		AuthorIsAssignedContributor: true,
		LinkedToGrainHackIssue:      true,
		CIPassed:                    &failing,
		Stats:                       DiffStats{MeaningfulLines: 50},
	}); !res.Rejected {
		t.Error("a failing-CI PR passed with zero-value toggles")
	}

	// Draft, zero-value toggles.
	if res := Prefilter(PrefilterInput{
		AuthorIsAssignedContributor: true,
		LinkedToGrainHackIssue:      true,
		IsDraft:                     true,
		Stats:                       DiffStats{MeaningfulLines: 50},
	}); !res.Rejected {
		t.Error("a draft PR passed with zero-value toggles")
	}
}

// Only an explicit "false" relaxes a §2.4 requirement. A missing, empty or
// malformed value keeps it enforced - the direction that cannot widen who
// qualifies for money by accident.
func TestPrefilterConfig_OnlyExplicitFalseRelaxes(t *testing.T) {
	for _, cfg := range []map[string]string{
		nil,
		{},
		{"qualifying_pr_requires_ci_pass": ""},
		{"qualifying_pr_requires_ci_pass": "no"},
		{"qualifying_pr_requires_ci_pass": "0"},
		{"qualifying_pr_requires_ci_pass": "true"},
	} {
		allowCI, allowUnlinked, allowDraft := PrefilterConfig(cfg)
		if allowCI || allowUnlinked || allowDraft {
			t.Errorf("cfg %v relaxed a requirement without an explicit false", cfg)
		}
	}

	allowCI, _, _ := PrefilterConfig(map[string]string{"qualifying_pr_requires_ci_pass": "false"})
	if !allowCI {
		t.Error(`an explicit "false" did not relax the CI requirement`)
	}
}
