package hackathon

import (
	"path"
	"strings"
)

// DiffStats is AI-specs.md §5.3's <diff_stats> block.
//
// §5.3 is emphatic that this is "computed in code, never estimated by the
// model. This is what stops verbosity gaming - nothing inside the diff can
// misrepresent its own size or generated-line ratio." So every field here is
// derived from the raw patch, and the judge is given the result rather than
// asked to work it out.
type DiffStats struct {
	FilesChanged    int  `json:"files_changed"`
	LinesAdded      int  `json:"lines_added"`
	LinesRemoved    int  `json:"lines_removed"`
	GeneratedLines  int  `json:"generated_lines"`
	LockfileLines   int  `json:"lockfile_lines"`
	TestLines       int  `json:"test_lines"`
	TestsAdded      bool `json:"tests_added"`
	TouchesCorePath bool `json:"touches_core_paths"`
	// MeaningfulLines excludes generated, lockfile and whitespace-only
	// changes. This is the number §3.5's qualifying_pr_min_meaningful_lines
	// is compared against, not the raw total.
	MeaningfulLines int  `json:"meaningful_lines"`
	DocsOnly        bool `json:"docs_only"`
}

// FileChange is one file's contribution to a PR, as the caller extracts it
// from the GitHub API. Kept deliberately small so ComputeDiffStats is a pure
// function over data rather than something that needs a GitHub client.
type FileChange struct {
	Filename  string
	Additions int
	Deletions int
	// Patch is the unified diff for this file; empty for binary files or
	// when GitHub omits it on very large diffs.
	Patch string
}

var lockfileNames = map[string]bool{
	"package-lock.json": true, "yarn.lock": true, "pnpm-lock.yaml": true,
	"go.sum": true, "Cargo.lock": true, "poetry.lock": true, "Gemfile.lock": true,
	"composer.lock": true, "Pipfile.lock": true, "bun.lockb": true,
}

var generatedMarkers = []string{
	"code generated by", "@generated", "do not edit", "auto-generated", "autogenerated",
}

var docExtensions = map[string]bool{
	".md": true, ".mdx": true, ".rst": true, ".txt": true, ".adoc": true,
}

func isLockfile(name string) bool { return lockfileNames[path.Base(name)] }

func isDocFile(name string) bool {
	if docExtensions[strings.ToLower(path.Ext(name))] {
		return true
	}
	lower := strings.ToLower(name)
	return strings.HasPrefix(lower, "docs/") || strings.Contains(lower, "/docs/")
}

func isTestFile(name string) bool {
	lower := strings.ToLower(name)
	base := path.Base(lower)
	return strings.HasSuffix(base, "_test.go") ||
		strings.Contains(base, ".test.") || strings.Contains(base, ".spec.") ||
		strings.HasPrefix(lower, "test/") || strings.HasPrefix(lower, "tests/") ||
		strings.Contains(lower, "/test/") || strings.Contains(lower, "/tests/") ||
		strings.Contains(lower, "__tests__/")
}

// isGeneratedPatch looks for the conventional generated-file banners inside
// the patch itself, so a generated file counts as generated even when its
// path looks ordinary.
func isGeneratedPatch(patch string) bool {
	head := patch
	if len(head) > 2000 {
		head = head[:2000]
	}
	lower := strings.ToLower(head)
	for _, marker := range generatedMarkers {
		if strings.Contains(lower, marker) {
			return true
		}
	}
	return false
}

// corePathHints are the directories where a change is more likely to be real
// logic than surface. Only a hint for the judge (§5.3's touches_core_paths),
// never a bucket by itself.
var corePathHints = []string{"/internal/", "/src/", "/lib/", "/pkg/", "/core/", "/server/", "/api/"}

func touchesCorePath(name string) bool {
	lower := "/" + strings.ToLower(strings.TrimPrefix(name, "/"))
	for _, hint := range corePathHints {
		if strings.Contains(lower, hint) {
			return true
		}
	}
	return false
}

// countPatchLines walks a unified diff, returning added/removed counts and
// how many added lines were whitespace-only.
func countPatchLines(patch string) (added, removed, whitespaceOnly int) {
	for _, line := range strings.Split(patch, "\n") {
		switch {
		case strings.HasPrefix(line, "+++") || strings.HasPrefix(line, "---"):
			// File headers, not content.
		case strings.HasPrefix(line, "+"):
			added++
			if strings.TrimSpace(line[1:]) == "" {
				whitespaceOnly++
			}
		case strings.HasPrefix(line, "-"):
			removed++
		}
	}
	return added, removed, whitespaceOnly
}

// ComputeDiffStats derives §5.3's diff_stats from the raw file changes.
// Pure function: no DB, no GitHub, no model.
func ComputeDiffStats(files []FileChange) DiffStats {
	var s DiffStats
	s.FilesChanged = len(files)
	docFiles, contentFiles := 0, 0

	for _, f := range files {
		added, removed, whitespace := countPatchLines(f.Patch)
		// GitHub's own additions/deletions are authoritative when the patch
		// is absent (binary or truncated).
		if f.Patch == "" {
			added, removed = f.Additions, f.Deletions
		}
		s.LinesAdded += added
		s.LinesRemoved += removed

		switch {
		case isLockfile(f.Filename):
			s.LockfileLines += added
		case isGeneratedPatch(f.Patch):
			s.GeneratedLines += added
		default:
			// Whitespace-only additions are real lines but not meaningful
			// ones - reformatting a file must not read as substance.
			s.MeaningfulLines += added - whitespace
			contentFiles++
		}

		if isTestFile(f.Filename) {
			s.TestLines += added
			if added > 0 {
				s.TestsAdded = true
			}
		}
		if isDocFile(f.Filename) {
			docFiles++
		}
		if touchesCorePath(f.Filename) {
			s.TouchesCorePath = true
		}
	}

	if s.MeaningfulLines < 0 {
		s.MeaningfulLines = 0
	}
	s.DocsOnly = docFiles > 0 && docFiles == len(files)
	_ = contentFiles
	return s
}

// PrefilterInput is everything §5.1 needs to decide, without a model.
type PrefilterInput struct {
	Stats DiffStats
	// CIPassed is nil when CI status is unknown - which is not the same as
	// failing, and must not be treated as such.
	CIPassed *bool
	// LinkedToGrainHackIssue is false when the PR resolves no GrainHack
	// issue (§2.4 requirement 3).
	LinkedToGrainHackIssue bool
	// AuthorIsAssignedContributor is §2.4 requirement 5, and the single
	// most important one: a PR from someone never assigned through
	// Grainlify does not qualify, however good it is.
	AuthorIsAssignedContributor bool
	AuthorIsIssueAuthor         bool
	AuthorIsRepoAdmin           bool
	// IssueWasDocsIssue exempts a docs-only PR from the docs-only rejection,
	// per §5.1's own parenthetical.
	IssueWasDocsIssue  bool
	MinMeaningfulLines int
}

// PrefilterResult is stage 1's verdict.
type PrefilterResult struct {
	Rejected bool
	Reason   string
}

// Prefilter implements AI-specs.md §5.1. Plain code, no tokens.
//
// Order matters only for which reason gets reported; any single failure is
// enough. The eligibility checks come first because they are the ones a
// contributor most needs stated plainly - "you were never assigned this"
// is a different conversation from "this PR was too small".
func Prefilter(in PrefilterInput) PrefilterResult {
	if !in.AuthorIsAssignedContributor {
		return PrefilterResult{true, "The PR author was not the contributor assigned this issue through Grainlify."}
	}
	if !in.LinkedToGrainHackIssue {
		return PrefilterResult{true, "The PR is not linked to a GrainHack issue."}
	}
	if in.AuthorIsIssueAuthor {
		return PrefilterResult{true, "The PR author opened the issue."}
	}
	if in.AuthorIsRepoAdmin {
		return PrefilterResult{true, "The PR author is an admin of the repository."}
	}
	// Explicitly false, not merely unknown: an unknown CI state is not a
	// failing one, and rejecting on it would punish repos with no CI.
	if in.CIPassed != nil && !*in.CIPassed {
		return PrefilterResult{true, "CI was failing at merge."}
	}
	if in.Stats.DocsOnly && !in.IssueWasDocsIssue {
		return PrefilterResult{true, "The PR changes documentation only, and the issue was not a documentation issue."}
	}
	if in.Stats.MeaningfulLines == 0 {
		return PrefilterResult{true, "The PR contains no meaningful code changes - only generated, lockfile, or whitespace edits."}
	}
	if in.MinMeaningfulLines > 0 && in.Stats.MeaningfulLines < in.MinMeaningfulLines {
		return PrefilterResult{true, "The PR is below this event's minimum meaningful-change size."}
	}
	return PrefilterResult{}
}
