package grainhack

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"errors"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
)

// The golden vectors are the cross-check between this package, the bounty
// agent and the grainhack-signer: a fixed key, fixed statements, and the exact
// canonical string and signature each must produce or accept. If this test
// fails, the canonical form changed - which breaks every verifier - unless all
// three were changed together on purpose.
//
// Regenerate (only for a deliberate, coordinated change):
//
//	GRAINHACK_GOLDEN_UPDATE=1 go test ./internal/grainhack -run TestGolden
const goldenPath = "testdata/grainhack_results_golden.json"

type goldenVector struct {
	Name            string `json:"name"`
	Statement       string `json:"statement"`
	StatementSHA256 string `json:"statement_sha256"`
	Signature       string `json:"signature_b64"`
}

type goldenFile struct {
	Note      string         `json:"note"`
	Domain    string         `json:"domain"`
	SeedB64   string         `json:"signing_key_seed_b64"`
	PublicKey string         `json:"public_key_b64"`
	Message   string         `json:"signed_message_is"`
	Vectors   []goldenVector `json:"vectors"`
}

// goldenSeed is 0x00..0x1f. A test key, never a real one.
func goldenSeed() []byte {
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i)
	}
	return seed
}

func mustUUID(s string) uuid.UUID { return uuid.MustParse(s) }

func goldenStatements() map[string]Statement {
	prev := mustUUID("11111111-1111-4111-8111-111111111111")
	return map[string]Statement{
		"basic": {
			StatementID:   prev,
			HackathonID:   mustUUID("22222222-2222-4222-8222-222222222222"),
			HackathonName: "GrainHack #1",
			Pool:          PoolContributor,
			ComputationID: mustUUID("33333333-3333-4333-8333-333333333333"),
			Currency:      CurrencyUSDC,
			Network:       NetworkSolanaDevnet,
			PoolMinor:     big.NewInt(10_000_000),
			// Deliberately out of order: the canonical form sorts them.
			Lines: []Line{
				{GitHubUserID: 583231, Login: "octocat", AmountMinor: big.NewInt(4_000_000), Status: StatusPayable},
				{GitHubUserID: 9919, Login: "github", AmountMinor: big.NewInt(6_000_000), Status: StatusHeldKYC},
			},
			IssuedAt: time.Date(2026, 10, 3, 12, 0, 0, 0, time.UTC),
		},
		"supersedes_and_escaping": {
			StatementID:   mustUUID("44444444-4444-4444-8444-444444444444"),
			Supersedes:    &prev,
			HackathonID:   mustUUID("22222222-2222-4222-8222-222222222222"),
			HackathonName: "Grain\"Hack\" — café <&> \\ \n\t\u0001\u007f   ✓ 🌾",
			Pool:          PoolContributor,
			ComputationID: mustUUID("33333333-3333-4333-8333-333333333333"),
			Currency:      CurrencyUSDC,
			Network:       NetworkSolanaMainnet,
			PoolMinor:     big.NewInt(4_000_000),
			Lines: []Line{
				{GitHubUserID: 9007199254740991, Login: "max-safe", AmountMinor: big.NewInt(1), Status: StatusPayable},
				{GitHubUserID: 2, Login: "b", AmountMinor: big.NewInt(2_999_999), Status: StatusPayable},
				{GitHubUserID: 1, Login: "a", AmountMinor: big.NewInt(1_000_000), Status: StatusHeldKYC},
			},
			// Sub-second and non-UTC on purpose: written as whole seconds, UTC.
			IssuedAt: time.Date(2026, 10, 3, 17, 30, 5, 999_000_000, time.FixedZone("IST", 5*3600+1800)),
		},
	}
}

func TestGolden(t *testing.T) {
	key := ed25519.NewKeyFromSeed(goldenSeed())
	stmts := goldenStatements()
	names := []string{"basic", "supersedes_and_escaping"}

	got := goldenFile{
		Note: "GrainHack results statement test vectors. Test key only (seed 0x00..0x1f); never used for real statements. " +
			"Generated by internal/grainhack/statement_test.go in Grainlify-Backend.",
		Domain:    SignatureDomain,
		SeedB64:   base64.StdEncoding.EncodeToString(goldenSeed()),
		PublicKey: PublicKeyB64(key),
		Message:   "UTF-8 bytes of domain + statement; signature is Ed25519, standard base64",
	}
	for _, n := range names {
		canonical, err := stmts[n].Canonical()
		if err != nil {
			t.Fatalf("%s: %v", n, err)
		}
		got.Vectors = append(got.Vectors, goldenVector{
			Name: n, Statement: canonical, StatementSHA256: SHA256Hex(canonical), Signature: Sign(key, canonical),
		})
	}

	if os.Getenv("GRAINHACK_GOLDEN_UPDATE") == "1" {
		var buf bytes.Buffer
		enc := json.NewEncoder(&buf)
		enc.SetEscapeHTML(false) // readable: "<&>" rather than \u003c\u0026\u003e
		enc.SetIndent("", "  ")
		if err := enc.Encode(got); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.FromSlash(goldenPath), buf.Bytes(), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	raw, err := os.ReadFile(filepath.FromSlash(goldenPath))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var want goldenFile
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if want.Domain != got.Domain || want.PublicKey != got.PublicKey || want.SeedB64 != got.SeedB64 {
		t.Fatalf("golden key/domain changed:\n got %+v\nwant %+v", got, want)
	}
	if len(want.Vectors) != len(got.Vectors) {
		t.Fatalf("golden has %d vectors, generated %d", len(want.Vectors), len(got.Vectors))
	}
	pub := key.Public().(ed25519.PublicKey)
	for i, w := range want.Vectors {
		g := got.Vectors[i]
		if g.Statement != w.Statement {
			t.Errorf("%s: canonical JSON changed\n got %s\nwant %s", w.Name, g.Statement, w.Statement)
		}
		if g.Signature != w.Signature {
			t.Errorf("%s: signature changed\n got %s\nwant %s", w.Name, g.Signature, w.Signature)
		}
		if g.StatementSHA256 != w.StatementSHA256 {
			t.Errorf("%s: sha256 changed", w.Name)
		}
		if !Verify(pub, w.Statement, w.Signature) {
			t.Errorf("%s: the golden signature does not verify", w.Name)
		}
	}
}

func TestCanonical_ExactShape(t *testing.T) {
	c, err := goldenStatements()["basic"].Canonical()
	if err != nil {
		t.Fatal(err)
	}
	want := `{"computation_id":"33333333-3333-4333-8333-333333333333","currency":"USDC",` +
		`"hackathon_id":"22222222-2222-4222-8222-222222222222","hackathon_name":"GrainHack #1",` +
		`"issued_at":"2026-10-03T12:00:00Z","kind":"grainhack_results",` +
		`"lines":[{"amount_minor":"6000000","github_user_id":9919,"login":"github","status":"held_kyc"},` +
		`{"amount_minor":"4000000","github_user_id":583231,"login":"octocat","status":"payable"}],` +
		`"network":"solana-devnet","pool":"contributor","pool_minor":"10000000",` +
		`"statement_id":"11111111-1111-4111-8111-111111111111","supersedes":null,"v":1}`
	if c != want {
		t.Fatalf("canonical\n got %s\nwant %s", c, want)
	}
}

// Escaping is JSON.stringify's, not encoding/json's: <, >, &, U+2028 and DEL
// are written as themselves; control characters below 0x20 use the short form
// or \u00xx in lowercase. And the result is still JSON that decodes back to
// the original string.
func TestCanonical_StringEscapingMatchesJSONStringify(t *testing.T) {
	st := goldenStatements()["supersedes_and_escaping"]
	c, err := st.Canonical()
	if err != nil {
		t.Fatal(err)
	}
	wantName := `"hackathon_name":"Grain\"Hack\" — café <&> \\ \n\t\u0001` + "\u007f   ✓ 🌾" + `"`
	if !strings.Contains(c, wantName) {
		t.Fatalf("hackathon_name not escaped as JSON.stringify would:\n%s", c)
	}
	if !strings.Contains(c, `"issued_at":"2026-10-03T12:00:05Z"`) {
		t.Fatalf("issued_at not whole-second UTC: %s", c)
	}
	if !strings.Contains(c, `"supersedes":"11111111-1111-4111-8111-111111111111"`) {
		t.Fatalf("supersedes missing: %s", c)
	}
	var back map[string]any
	if err := json.Unmarshal([]byte(c), &back); err != nil {
		t.Fatalf("canonical is not JSON: %v", err)
	}
	if back["hackathon_name"] != st.HackathonName {
		t.Fatalf("hackathon_name round-trips to %q", back["hackathon_name"])
	}
	if strings.ContainsAny(c, " \n\t") && !strings.Contains(c, "café <&> ") {
		t.Fatal("whitespace outside strings")
	}
}

func TestCanonical_LineOrderIsByGitHubUserID(t *testing.T) {
	a := goldenStatements()["basic"]
	b := a
	b.Lines = []Line{a.Lines[1], a.Lines[0]}
	ca, _ := a.Canonical()
	cb, _ := b.Canonical()
	if ca != cb {
		t.Fatal("input order changed the canonical form")
	}
	if a.Lines[0].GitHubUserID != 583231 {
		t.Fatal("Canonical reordered the caller's slice")
	}
}

func TestCanonical_Refusals(t *testing.T) {
	base := goldenStatements()["basic"]
	cases := map[string]func(s *Statement){
		"sum below pool": func(s *Statement) { s.PoolMinor = big.NewInt(10_000_001) },
		"duplicate winner": func(s *Statement) {
			s.Lines = []Line{s.Lines[0], s.Lines[0]}
			s.PoolMinor = big.NewInt(8_000_000)
		},
		"zero amount": func(s *Statement) { s.Lines = []Line{s.Lines[0], {9919, "github", big.NewInt(0), StatusPayable}} },
		"unknown status": func(s *Statement) {
			s.Lines = []Line{s.Lines[0], {9919, "github", big.NewInt(6_000_000), "awaiting_wallet"}}
		},
		"unknown network":  func(s *Statement) { s.Network = "base-sepolia" },
		"other currency":   func(s *Statement) { s.Currency = "ANSEM" },
		"maintainer typo":  func(s *Statement) { s.Pool = "maintainers" },
		"no lines":         func(s *Statement) { s.Lines = nil },
		"empty login":      func(s *Statement) { s.Lines = []Line{s.Lines[0], {9919, "", big.NewInt(6_000_000), StatusPayable}} },
		"unsafe id":        func(s *Statement) { s.Lines = []Line{s.Lines[0], {1 << 53, "x", big.NewInt(6_000_000), StatusPayable}} },
		"invalid utf8":     func(s *Statement) { s.HackathonName = "bad\xff" },
		"self supersede":   func(s *Statement) { id := s.StatementID; s.Supersedes = &id },
		"missing issuedAt": func(s *Statement) { s.IssuedAt = time.Time{} },
	}
	for name, mutate := range cases {
		s := base
		s.Lines = append([]Line(nil), base.Lines...)
		mutate(&s)
		if _, err := s.Canonical(); !errors.Is(err, ErrInvalidStatement) {
			t.Errorf("%s: err = %v, want ErrInvalidStatement", name, err)
		}
	}
}

func TestSignature_DomainAndKey(t *testing.T) {
	key, err := ParseSigningKey(base64.StdEncoding.EncodeToString(goldenSeed()))
	if err != nil || key == nil {
		t.Fatalf("parse: %v", err)
	}
	c, _ := goldenStatements()["basic"].Canonical()
	sig := Sign(key, c)
	pub := key.Public().(ed25519.PublicKey)
	if !Verify(pub, c, sig) {
		t.Fatal("does not verify")
	}
	// Not valid without the domain, nor under another domain.
	raw, _ := base64.StdEncoding.DecodeString(sig)
	if ed25519.Verify(pub, []byte(c), raw) {
		t.Fatal("signature verifies without the domain prefix")
	}
	if ed25519.Verify(pub, []byte("grainlify-bounty-wallet-link:v1\n"+c), raw) {
		t.Fatal("signature verifies under the bounty link domain")
	}
	if Verify(pub, c+" ", sig) {
		t.Fatal("signature verifies for a different statement")
	}

	if k, err := ParseSigningKey("  "); k != nil || err != nil {
		t.Fatalf("empty key: %v %v", k, err)
	}
	for _, bad := range []string{"not-base64!", base64.StdEncoding.EncodeToString([]byte("short"))} {
		if _, err := ParseSigningKey(bad); err == nil {
			t.Errorf("ParseSigningKey(%q) accepted", bad)
		}
	}
}
